---
title: "Evaluate decision tree models on out-of-sample data"
author: "Esben Lykke"
date: "21/12/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(
  tidyverse,
  tidymodels,
  here,
  ggthemes
)
```

# Import malthe_nw
```{r}
malthe_nw <-
  read_rds(here("data", "malthe_nw.rds"))
```

# Load tecision tree models
```{r}
tree_fit_full <-
  read_rds(here("models", "tree_fit_full_butch.rds"))

tree_fit_imp6 <-
  read_rds(here("models", "tree_fit_imp6_butch.rds"))

tree_fit_no_temp <-
  read_rds(here("models", "tree_fit_no_temp_butch.rds"))

tree_fit_no_temp_imp5 <-
  read_rds(here("models", "tree_fit_no_temp_imp5_butch.rds"))
```


# Tree model predictions on FASER thigh and hip data
```{r FASER thigh}
faser_test_thigh <-
  tree_fit_full %>%
  augment(faser_test_thigh) %>% 
  select(-.pred_0:-.pred_1, tree_full_pred = .pred_class)


faser_test_thigh <-
  tree_fit_imp6 %>%
  augment(faser_test_thigh) %>% 
  select(-.pred_0:-.pred_1, tree_imp6_pred = .pred_class)

faser_test_thigh <-
  tree_fit_no_temp %>%
  augment(faser_test_thigh) %>% 
  select(-.pred_0:-.pred_1, tree_no_temp_pred = .pred_class)

faser_test_thigh <-
  tree_fit_no_temp_imp5 %>%
  augment(faser_test_thigh) %>% 
  select(-.pred_0:-.pred_1, tree_no_temp_imp5_pred = .pred_class)
```

```{r FASER hip}
faser_test_hip <-
  tree_fit_full %>%
  augment(faser_test_hip) %>% 
  select(-.pred_0:-.pred_1, tree_full_pred = .pred_class)


faser_test_hip <-
  tree_fit_imp6 %>%
  augment(faser_test_hip) %>% 
  select(-.pred_0:-.pred_1, tree_imp6_pred = .pred_class)

faser_test_hip <-
  tree_fit_no_temp %>%
  augment(faser_test_hip) %>% 
  select(-.pred_0:-.pred_1, tree_no_temp_pred = .pred_class)

faser_test_hip <-
  tree_fit_no_temp_imp5 %>%
  augment(faser_test_hip) %>% 
  select(-.pred_0:-.pred_1, tree_no_temp_imp5_pred = .pred_class)
```
